baseURL = 'https://sqlfluff.com/'
languageCode = 'en-us'
title = 'SQLFluff'
staticDir = ['static', 'vendor/sqlfluff-design/static']

# Automatically generate robots.txt
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  description = "The SQL linter for humans"
  metaKeywords = ["sqlfluff", "sql", "linter"]
  showStats = true
  socialIcons = [
    {name = "github", label = "GitHub", url = "https://github.com/sqlfluff"},
    {name = "docker", label = "Docker Hub", url = "https://hub.docker.com/r/sqlfluff/sqlfluff"},
    {name = "python", label = "PyPI", url = "https://pypi.org/org/SQLFluff/"},
    {name = "twitter", label = "Twitter", url = "https://twitter.com/SQLFluff"},
    {name = "bluesky", label = "Bluesky", url = "https://bsky.app/profile/sqlfluff.com"},
    {name = "linkedin", label = "LinkedIn", url = "https://linkedin.com/company/sqlfluff"},
    {name = "slack", label = "Slack", url = "https://join.slack.com/t/sqlfluff/shared_invite/zt-3qprhrisj-ClUo_1tLmYBzrVu5ZoDwIw"},
    {name = "stackoverflow", label = "Stack Overflow", url = "https://stackoverflow.com/questions/tagged/sqlfluff"},
  ]

  [params.links]
    docs = "https://docs.sqlfluff.com"
    stats = "/stats/"
    source = "https://github.com/sqlfluff/sqlfluff"
