[build]
  # https://gohugo.io/hosting-and-deployment/hosting-on-netlify/
  # Recommended settings from docs
  # --gc means garbage collect
  # --minify mean it will minify any files that it can
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.4"
  TZ = "Europe/London"

[[redirects]]
  from = "/stats/*"
  to = "https://brilliant-naiad-526a97.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/stats"
  to = "/stats/"
  status = 301
  force = true
